import type { Metadata } from "next"
import Navbar from "@/components/Navbar"
import "./globals.css"
import QueryProvider from "../components/QueryProvider"

export const metadata: Metadata = {
  title: "Wash World app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
    <html
      lang="da"
      className="h-full antialiased"
    >
      <body className="h-full">
        {children}
        <Navbar />
      </body>
    </html>
    </QueryProvider>
  );
}
